name: sapp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py311h2e04523_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py311hed34c8f_2
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - appdirs==1.4.4
      - argparse-dataclass==2.0.0
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - conda-inject==1.3.2
      - configargparse==1.7.1
      - connection-pool==0.0.3
      - docutils==0.22.4
      - dpath==2.2.0
      - fastjsonschema==2.21.2
      - gitdb==4.0.12
      - gitpython==3.1.46
      - humanfriendly==10.0
      - idna==3.11
      - immutables==0.21
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - markupsafe==3.0.3
      - nbformat==5.10.4
      - packaging==25.0
      - platformdirs==4.5.1
      - psutil==7.2.1
      - pulp==3.3.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - reretry==0.11.8
      - rpds-py==0.30.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - snakemake==9.14.8
      - snakemake-interface-common==1.22.0
      - snakemake-interface-executor-plugins==9.3.9
      - snakemake-interface-logger-plugins==2.0.0
      - snakemake-interface-report-plugins==1.3.0
      - snakemake-interface-scheduler-plugins==2.0.2
      - snakemake-interface-storage-plugins==4.3.2
      - tabulate==0.9.0
      - throttler==1.2.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - wrapt==2.0.1
      - yte==1.9.4
